Exception: Add Exceptions for forthcoming DAO implementation
There aren't many distinct types of errors, however there are many
different instances. Here's what we have thus far.

MpDbException: Created to be the parent of all exceptions that are to
  be (possibly) presented to the user by the client. For now only
  DAOException and ValidationException extend this class.

DAOException: Base exception type, everything should extend this

GenericDAOException: When you don't know what else to use, use this
  with some some appropriate text. (Hopefully in practice this won't
  be relied upon but instead is just a fall back)

FunctionNotImplementedException: There are times when we don't
  implement various functions in the DAO (for instance, we never want
  to delete() an element, elements are from a static list), whenever
  a function isn't implemented it should throw this exception. This
  way if someone calls the function accidentally a semi-understandable
  error will result, instead of the function just returning null, or
  something similar.

*NotFoundException: Generally an object will be presented to the
  DAO code saying "Here's an object, I think there is enough
  information in there for you to obtain the rest of the details from
  the db. Go do that." However, if they are mistaken the appropriate
  version of this exception is thrown.

*AlreadyExistsException: When we tried to commit an object that already
  exists in the database. These will generally follow very closely with
  the unique constraints in the database.