Exception: Move all ValidationExceptions into their own package
Instead of keeping all exceptions in one package, create a subpackage
for all of the validation exceptions. Hopefully this will help things
be a bit more organized and cleaner.